repos:
-   repo: local
    hooks:
    -   id: pytest-e2e
        name: pytest-e2e
        entry: ./run_e2e.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [push] 