repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
    -   id: pytest-e2e
        name: pytest-e2e
        entry: pytest tests/e2e
        language: system
        pass_filenames: false
        always_run: true
        stages: [push] 